spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calculator?serverTimezone=UTC
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8999