spring:
  datasource:
    url: jdbc:mysql://localhost:3308/calculator?serverTimezone=UTC
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-uat.yaml

server:
  port: 8888
